### ISSUE TITLE
How do I use wiktionary cli with another language?

### ISSUE THREAD

**Issue by mountwebs** [words/wiktionary#3]
(WIth npx)

Thanks!

**Comment by zeke** [comment]
Hi there! I don't think the CLI has support for that, but it could!  The module itself has support for it. Would you be interested in opening a PR to add support for a `--lang=es` flag, or something like it?

**Comment by zeke** [comment]
Hey look! This feature was added by @dorian-marchal in https://github.com/words/wiktionary/pull/4 🎉
