### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by dylantientcheu** [words/wiktionary#7]
I experience a CORS issue whenever I run the request with Wiktionary from localhost but when this is run from npm RunKit it works well.

![image](https://user-images.githubusercontent.com/26802924/65833945-e0406380-e2cd-11e9-83e6-4bfd4f6a1cd0.png)

**Comment by dylantientcheu** [comment]
This [stackoverflow](https://stackoverflow.com/a/38921370/5268119) answer helped me fix this.

I added `origin:"*"` in your `index.js` file.

If this hasn't been reported since then, maybe there's a better way to deal with this. 

Nonetheless, I can submit a PR if you wish :)

**Comment by zeke** [comment]
Fixed by #8
